{% set name = "grib2io" %}
{% set version = "2.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/grib2io-{{ version }}.tar.gz
  sha256: 93d8d0db668d46fbaf5fe3ecf75c5c2c77f42d36e04515738e24ef3afaaccbcf

build:
  skip: true  # [py<38]
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy <2.0.0                           # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - nceplibs-g2c
  host:
    - python
    - cython >=0.29.16
    - setuptools >=61.0
    - numpy <2.0.0
    - pip
    - nceplibs-g2c
  run:
    - python
    - pyproj
    - nceplibs-g2c

test:
  imports:
    - grib2io
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NOAA-MDL/grib2io
  summary: Python interface to the NCEP G2C Library for reading/writing GRIB2 files.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TimothyCera-NOAA
    - EricEngle-NOAA
